import type { CardDef } from './types'

export const CARDS: Record<string, CardDef> = {
  foton: {
    id: 'foton',
    name: 'Fóton',
    title: 'O Estafeta · Sujeito nº 01',
    cost: 1,
    type: 'criatura',
    faces: [
      { label: 'Raio', attack: 2, health: 1, keywords: ['veloz'] },
      { label: 'Brilho', attack: 1, health: 2, keywords: [] },
    ],
    text: 'Entrega recados a 299.792 km/s. Nunca chegou atrasado; nunca chegou inteiro.',
    bio: 'Contratado como mensageiro. Cobra por distância percorrida, o que arruinou o Instituto.',
  },
  neutrino: {
    id: 'neutrino',
    name: 'Neutrina',
    title: 'A Intangível · Sujeito nº 02',
    cost: 1,
    type: 'criatura',
    faces: [
      { label: 'Fase', attack: 1, health: 1, keywords: ['fantasma'] },
      { label: 'Massa', attack: 1, health: 3, keywords: [] },
    ],
    text: 'Atravessa paredes, cofres e reuniões que poderiam ter sido e-mails.',
    bio: 'Atravessou você três trilhões de vezes hoje. Não pediu desculpa nenhuma delas.',
  },
  sentinela: {
    id: 'sentinela',
    name: 'Sentinela Q-88',
    title: 'Segurança do Arquivo',
    cost: 2,
    type: 'criatura',
    faces: [
      { label: 'Escudo', attack: 1, health: 4, keywords: ['barreira'] },
      { label: 'Lança', attack: 3, health: 2, keywords: [] },
    ],
    text: 'Robô de guarda do subsolo. O manual não diz se protege o arquivo de você ou você do arquivo.',
    bio: 'Modelo 1953. Roda em válvulas. Nunca dormiu em serviço porque nunca dormiu.',
  },
  eletron: {
    id: 'eletron',
    name: 'Elétron',
    title: 'O Inquieto · Sujeito nº 03',
    cost: 2,
    type: 'criatura',
    faces: [
      { label: 'Excitado', attack: 3, health: 1, keywords: [] },
      { label: 'Estável', attack: 2, health: 3, keywords: [] },
    ],
    text: 'Já foi demitido de sete orbitais por não ficar parado.',
    bio: 'Toma dezessete cafés por dia. Os cafés é que orbitam ele.',
  },
  gato: {
    id: 'gato',
    name: 'O Gato',
    title: 'Sujeito nº 13 · NÃO ABRA A CAIXA',
    cost: 3,
    type: 'criatura',
    faces: [
      { label: 'Vivo', attack: 4, health: 2, keywords: ['veloz'] },
      { label: 'Espectro', attack: 1, health: 6, keywords: ['barreira'] },
    ],
    text: 'Mascote não-oficial do Instituto. Oficialmente, duas mascotes.',
    bio: 'Herr Schrödinger o deixou aqui "só por uma semana", em 1935.',
  },
  colapsador: {
    id: 'colapsador',
    name: 'O Auditor',
    title: 'Fiscal de Realidades',
    cost: 4,
    type: 'criatura',
    onPlay: 'colapsarInimigo',
    faces: [
      { label: 'Vistoria', attack: 3, health: 4, keywords: [] },
      { label: 'Autuação', attack: 4, health: 3, keywords: [] },
    ],
    text: 'AO ENTRAR: colapsa um sujeito inimigo aleatório. O carimbo dele não pergunta.',
    bio: 'Chega sem avisar, olha para a sua função de onda e ela desiste.',
  },
  ondapiloto: {
    id: 'ondapiloto',
    name: 'Madame Onda',
    title: 'Regente do Salão de Interferência',
    cost: 4,
    type: 'criatura',
    faces: [
      { label: 'Crista', attack: 5, health: 3, keywords: [] },
      { label: 'Vale', attack: 3, health: 5, keywords: ['barreira'] },
    ],
    text: 'Rege o coro de probabilidades do terceiro subsolo com uma batuta de vidro.',
    bio: 'Já foi mar. Aposentou-se para algo mais violento: a acústica.',
  },
  quasar: {
    id: 'quasar',
    name: 'Quasar',
    title: 'O Farol · Sujeito nº 07',
    cost: 5,
    type: 'criatura',
    faces: [
      { label: 'Jato', attack: 6, health: 4, keywords: [] },
      { label: 'Halo', attack: 4, health: 6, keywords: [] },
    ],
    text: 'Ilumina o estacionamento do Instituto e três galáxias vizinhas.',
    bio: 'A conta de luz dele é paga em massa solar. Estamos atrasados.',
  },
  singularidade: {
    id: 'singularidade',
    name: 'A Fome',
    title: 'Sujeito nº 00 · CONTENÇÃO MÁXIMA',
    cost: 7,
    type: 'criatura',
    faces: [
      { label: 'Horizonte', attack: 8, health: 6, keywords: ['barreira'] },
      { label: 'Núcleo', attack: 6, health: 8, keywords: ['veloz'] },
    ],
    text: 'O primeiro sujeito catalogado. O catálogo original está dentro dela.',
    bio: 'Tudo que cruza o horizonte vira memória. Inclusive três estagiários.',
  },

  medicao: {
    id: 'medicao',
    name: 'Medição',
    title: 'Protocolo M-01',
    cost: 1,
    type: 'feitico',
    spell: 'medir',
    text: 'Colapsa qualquer sujeito em um estado aleatório.',
    bio: 'Olhar já é interferir. Assinar o formulário também.',
  },
  polarizacao: {
    id: 'polarizacao',
    name: 'Polarização',
    title: 'Protocolo P-02',
    cost: 2,
    type: 'feitico',
    spell: 'polarizar',
    text: 'Colapsa um sujeito SEU no estado que você escolher.',
    bio: 'O único formulário do Instituto em que você escolhe a resposta.',
  },
  emaranhar: {
    id: 'emaranhar',
    name: 'Emaranhamento',
    title: 'Protocolo E-03',
    cost: 2,
    type: 'feitico',
    spell: 'emaranhar',
    text: 'Vincula um sujeito seu a um inimigo: colapsam juntos; quando um morre, o outro sofre 2 de dano.',
    bio: 'Ação fantasmagórica à distância. Aprovada pelo RH em 1949.',
  },
  tunel: {
    id: 'tunel',
    name: 'Túnel Quântico',
    title: 'Protocolo T-04',
    cost: 2,
    type: 'feitico',
    spell: 'tunel',
    text: 'Um sujeito seu ganha Fantasma e Veloz até o fim do turno.',
    bio: 'Por que contornar a parede se existe uma probabilidade de você já estar do outro lado?',
  },
  pulso: {
    id: 'pulso',
    name: 'Pulso de Decaimento',
    title: 'Protocolo D-05',
    cost: 3,
    type: 'feitico',
    spell: 'pulso',
    text: 'Causa 3 de dano a qualquer alvo. Sujeitos em superposição colapsam antes.',
    bio: 'Meia-vida de tudo: metade do tempo que você acha que tem.',
  },
  decoerencia: {
    id: 'decoerencia',
    name: 'Decoerência',
    title: 'Protocolo Ω-06',
    cost: 5,
    type: 'feitico',
    spell: 'decoerencia',
    text: 'Colapsa TODOS os sujeitos inimigos e causa 2 de dano a cada um.',
    bio: 'O universo insiste em ser clássico. Às vezes nós ajudamos.',
  },
  flutuacao: {
    id: 'flutuacao',
    name: 'Requisição',
    title: 'Protocolo R-07',
    cost: 1,
    type: 'feitico',
    spell: 'flutuacao',
    text: 'Compre 2 fichas do arquivo.',
    bio: 'Do nada, tudo — desde que preenchido em três vias.',
  },
}

/** Lista de 20 fichas (defIds) usada pelos dois lados */
export const DECK_LIST: string[] = [
  'foton', 'foton',
  'neutrino',
  'sentinela', 'sentinela',
  'eletron', 'eletron',
  'gato', 'gato',
  'colapsador',
  'ondapiloto',
  'quasar',
  'singularidade',
  'medicao',
  'polarizacao',
  'emaranhar',
  'tunel',
  'pulso',
  'decoerencia',
  'flutuacao',
]

export function getDef(defId: string): CardDef {
  const def = CARDS[defId]
  if (!def) throw new Error(`ficha desconhecida: ${defId}`)
  return def
}
